name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: axwgkpue2ufo/ocilabs/streaming
          tags: latest
          registry: sjc.ocir.io
          dockerfile: Dockerfile
          username: ${{ secrets.OCIR_USER }}
          password: ${{ secrets.OCIR_PWD }}
