name: Deploy to OKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Bastion Session
      run: |
        # Create a new bastion session
        session_id=$(oci --region ${REGION} compute bastion create-session --instance-id ${INSTANCE_ID} --authorized-key-file id_rsa.pub --fingerprint ${FINGERPRINT} --query 'data.id' --output text)

        # Wait for the session to become active
        while true; do
          status=$(oci --region ${REGION} compute bastion get-session --session-id ${session_id} --query 'data."session-state"' --output text)
          if [ "$status" = "ACTIVE" ]; then
            break
          fi
          sleep 5
        done

        # Get the session's connection string
        connection_string=$(oci --region ${REGION} compute bastion get-session-connection-string --session-id ${session_id} --query 'data."connection-string"' --output text)

        # Connect to the bastion host
        ssh -o "StrictHostKeyChecking no" -i id_rsa ${connection_string}

    - name: Deploy to OKE
      run: |
        kubectl --kubeconfig=${KUBECONFIG} apply -f ${DEPLOYMENT_FILE}
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        DEPLOYMENT_FILE: path/to/deployment.yaml
      
    - name: Delete Bastion Session
      run: |
        # Delete the bastion session
        oci --region ${REGION} compute bastion delete-session --session-id ${session_id}
      env:
        session_id: ${{ steps.Create_Bastion_Session.outputs.session_id }}
